export const ADD_INFO_START = 'ADD_INFO_START';
export const ADD_INFO_SUCCESS = 'ADD_INFO_SUCCESS';
export const ADD_INFO_FAIL = 'ADD_INFO_FAIL';
export const INFO_INIT = 'INFO_INIT';

export const FETCH_INFO_FAIL = 'FETCH_INFO_FAIL';
export const FETCH_INFO_START = 'FETCH_INFO_START';
export const FETCH_INFO_SUCCESS = 'FETCH_INFO_SUCCESS';